# Generated by Django 2.2.9 on 2020-01-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
                ('message_string', models.CharField(max_length=100)),
            ],
        ),
    ]
